<!DOCTYPE html>
<div id="footer_wrap" class="outer">
  <footer class="inner">
    <p class="copyright">MDsrv maintained by <a target="_blank" href="https://github.com/arose">arose</a> & <a target="_blank" href="https://github.com/j0kaso">j0kaso</a>
    - Generated by <a target="_blank" href="https://pages.github.com">GitHub Pages</a></p>
  </footer>
</div>